---
driver:
  name: ec2
  require_chef_omnibus: latest
  aws_ssh_key_id: <%= ENV['AWS_EC2_KEYPAIR'] %>
  associate_public_ip: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  security_group_ids: <%= ENV['AWS_EC2_SG'].split(',').to_s %>
transport:
  ssh_key: <%= ENV['AWS_EC2_KEYPASS'] %>
  username: ec2-user

platforms:
# - name: amazon-linux-micro-tokyo
#   driver:
#     instance_type: t3.micro
#     image_id: ami-0c3fd0f5d33134a76 # Amazon Linux 2 AMI (HVM), SSD Volume Type
#     region: ap-northeast-1
#     availability_zone: ap-northeast-1a
#     tags:
#       Name: test-kitchen-micro
- name: amazon-linux-large-tokyo
  driver:
    instance_type: c5.large
    image_id: ami-0c3fd0f5d33134a76 # Amazon Linux 2 AMI (HVM), SSD Volume Type
    region: ap-northeast-1
    availability_zone: c
    tags:
      Name: test-kitchen-large

provisioner:
  name: chef_zero
  require_chef_omnibus: 15.1.36

verifier:
  name: shell

suites:
- name: amimoto
  run_list:
    - recipe[amimoto::repos]
    - recipe[amimoto::nginx]
    - recipe[amimoto::update-motd]
    - recipe[amimoto::default]
    - recipe[amimoto::nginx_default]
    - recipe[amimoto::wordpress]
  attributes:
    phpfpm:
      version: "73"
    redis:
      enabled: true
    wordpress:
      db:
        user_name: kitchen
